name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

# GitHub Pagesへのデプロイに必要な権限を設定
permissions:
  contents: read
  pages: write
  id-token: write

# 同時実行を制限（新しいデプロイが開始されたら古いものをキャンセル）
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          enablement: true

      - name: Install dependencies
        run: npm ci

      - name: Clean up conflicting config files
        run: |
          if [ -f "next.config.js" ]; then
            echo "Removing conflicting next.config.js file"
            rm next.config.js
          fi
          echo "Using next.config.ts"

      - name: Build with Next.js
        run: npm run build
        env:
          GITHUB_PAGES: true
          NEXT_PUBLIC_GA_TRACKING_ID: G-7Z5Q5R9ND4
          NEXT_PUBLIC_SITE_URL: https://www.japonchaines.net
          NEXT_PUBLIC_ADSENSE_CLIENT_ID: ca-pub-6564351127136787
          NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: WSc4lTmbOgAvZGsqzxJTO3PmxtWXH-AdYFhZNvXnlxY

      - name: List build output
        run: |
          echo "Listing current directory:"
          ls -la
          echo "Checking if docs folder exists:"
          if [ -d "docs" ]; then
            echo "docs folder found, listing contents:"
            ls -la docs/
            echo "Total files in docs:"
            find docs -type f | wc -l
          else
            echo "docs folder not found"
            echo "Checking .next folder:"
            if [ -d ".next" ]; then
              echo ".next folder found, listing contents:"
              ls -la .next/
            fi
            echo "Available directories:"
            ls -la | grep "^d"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
        # mainブランチでのみアーティファクトをアップロード
        if: github.ref == 'refs/heads/main'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # mainブランチでのみデプロイを実行
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
